---
title: "Contraction"
author: "J. Fischer Ehmsen"
date: "2025-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cmdstanr)
library(posterior)
library(patchwork)

source(here::here("scripts","utility.R"))
Extero_Normal_mm<-readRDS(here::here("results","Fit population","Extero_Normal_mm.RDS"))
RRST_weibull_priors<-readRDS(here::here("results","Fit population","RRST_weibull_priors.RDS"))

```

```{r, fig.width=12,fig.height=6}


n_draws = 10000
priors <- tibble(
  variable = c(
    "gm[1]", "gm[2]", "gm[3]", "gm[4]", "gm[5]",
    "tau_u[1]", "tau_u[2]", "tau_u[3]", "tau_u[4]", "tau_u[5]"
  ),
  mean = c(
    -1.3, 0, 0, 0, -4,
     0,   0, 0, 0,  0
  ),
  sd = c(
     1.3, 3, 50, 50, 2,
     1.3, 1.3, 50, 50, 2
  )
)

draws_df <- priors %>%
  mutate(draws = map2(mean, sd, ~ rnorm(n_draws, .x, .y))) %>%
  unnest(draws)

prior_sd <- draws_df %>%
  group_by(variable) %>%
  summarise(
    pre_var = var(draws),
    .groups = "drop"
  )

post_sd = as_draws_df(Extero_Normal_mm$draws(c("gm","tau_u"))) %>% select(-contains(".")) %>% 
  pivot_longer(everything()) %>% group_by(name) %>% 
  summarize(post_var = sd(value)^2) %>% 
  rename(variable = name)

label_map <- c(
  "gm[1]"    = "μ[Slope]",
  "gm[2]"    = "μ[Slope[dif]]",
  "gm[3]"    = "μ[Threshold]",
  "gm[4]"    = "μ[Threshold[dif]]",
  "gm[5]"    = "μ[Lapse]",
  "tau_u[1]" = "σ[Slope]",
  "tau_u[2]" = "σ[Slope[dif]]",
  "tau_u[3]" = "σ[Threshold]",
  "tau_u[4]" = "σ[Threshold[dif]]",
  "tau_u[5]" = "σ[Lapse]"
)

grouplevel_con = inner_join(post_sd, prior_sd) %>%
  mutate(contraction = 1 - (post_var / pre_var)) %>%
  mutate(variable2 = recode(variable, !!!label_map)) %>%
  mutate(variable = "Grouplevel") %>% 
  ggplot(aes(x = variable2, y = contraction)) +
  geom_point() +
  geom_hline(aes(yintercept=1),alpha=.5,linetype='dotted')+
  geom_hline(aes(yintercept=0),alpha=.5,linetype='dotted')+
  scale_x_discrete(labels = function(x) parse(text = x)) +
  xlab("")+
  theme_classic()+
  facet_wrap(~variable, labeller = label_both)


```


```{r, fig.width=12,fig.height=6}

n_draws <- 10000

df <- tibble(
  variable = c(
    "gm[1]", "gm[2]", "gm[3]", "gm[4]", "gm[5]",
    "tau_u[1]", "tau_u[2]", "tau_u[3]", "tau_u[4]", "tau_u[5]"
  ),
  mean = c(
    -1.3, 0, 0, 0, -4,
     0,   0, 0, 0,  0
  ),
  sd = c(
     1.3, 3, 50, 50, 2,
     1.3, 1.3, 50, 50, 2
  )
) %>%
  mutate(
    p    = as.integer(str_extract(variable, "\\d+")),
    type = str_extract(variable, "^[a-z_]+")
  ) %>%
  select(p, type, mean, sd) %>%
  group_by(p, type) %>%
  summarise(
    draw = list(rnorm(n_draws, mean, sd)),
    .groups = "drop"
  ) %>%
  unnest(draw) %>%
  group_by(p, type) %>%
  mutate(draw_id = row_number()) %>%
  ungroup() %>%
  pivot_wider(
    names_from  = type,
    values_from = draw
  )

priorvar = df %>%
  mutate(
    z = rnorm(n()),
    theta = gm + tau_u * z,
    theta_name = paste0("theta[", p, "]")
  ) %>%
  group_by(theta_name) %>%
  summarise(prior_variance = var(theta)) %>% 
  ungroup() %>% 
  mutate(variable = ifelse(theta_name == "theta[1]","Slope",
                            ifelse(theta_name == "theta[2]","Slope_dif",
                                   ifelse(theta_name == "theta[3]","Threshold",
                                          ifelse(theta_name == "theta[4]","Threshold_dif",
                                                 ifelse(theta_name == "theta[5]","Lapse",NA))))),
         theta_name = NULL)



subject_lapse = as_draws_df(Extero_Normal_mm$draws(c("lapse_p"))) %>% 
  select(-contains(".")) %>% 
  mutate(draw = 1:n()) %>% 
    pivot_longer(-draw) %>% 
    mutate(
    subject = as.integer(str_match(name, "\\[(\\d+),(\\d+)\\]")[,3])
  ) %>% 
    group_by(subject) %>% 
  summarize(post_var = sd(value)^2) %>% 
  mutate(variable = "Lapse")

post_sd_sub = as_draws_df(Extero_Normal_mm$draws(c("param"))) %>% 
  select(-contains(".")) %>% 
  mutate(draw = 1:n()) %>% 
  pivot_longer(-draw) %>% 
    mutate(
    subject = as.integer(str_match(name, "\\[(\\d+),(\\d+)\\]")[,2]),
    variable = as.integer(str_match(name, "\\[(\\d+),(\\d+)\\]")[,3])
  ) %>% 
    group_by(subject,variable) %>% 
  summarize(post_var = sd(value)^2) %>% 
  mutate(variable = ifelse(variable == 1, "Slope",
                           ifelse(variable == 2, "Slope_dif",
                                  ifelse(variable == 3, "Threshold",
                                         ifelse(variable == 4, "Threshold_dif",NA)))))

subject_params = rbind(subject_lapse,post_sd_sub)

p1 = inner_join(priorvar, subject_params) %>% 
  mutate(contraction = 1 - (post_var / prior_variance)) %>% 
  ggplot(aes(x = subject, y = contraction))+
  geom_point(alpha = 0.3)+
  geom_hline(aes(yintercept=1),alpha=.5,linetype='dotted')+
  geom_hline(aes(yintercept=0),alpha=.5,linetype='dotted')+
  facet_wrap(~variable, scales = "free", labeller = label_both, ncol = 2)+
  theme_classic()

```

# combined

```{r, fig.width=12,fig.height=10}
get_plot = function(variable2, axis_title){
  
  if(axis_title){
    inner_join(priorvar, subject_params) %>% 
      filter(variable == variable2) %>% 
      mutate(contraction = 1 - (post_var / prior_variance)) %>% 
      ggplot(aes(x = subject, y = contraction))+
      geom_point(alpha = 0.3)+
      geom_hline(aes(yintercept=1),alpha=.5,linetype='dotted')+
      geom_hline(aes(yintercept=0),alpha=.5,linetype='dotted')+
      facet_wrap(~variable, scales = "free", labeller = label_both, ncol = 2)+
      theme_classic()
  }else{
    inner_join(priorvar, subject_params) %>% 
      filter(variable == variable2) %>% 
      mutate(contraction = 1 - (post_var / prior_variance)) %>% 
      ggplot(aes(x = subject, y = contraction))+
      geom_point(alpha = 0.3)+
      geom_hline(aes(yintercept=1),alpha=.5,linetype='dotted')+
      geom_hline(aes(yintercept=0),alpha=.5,linetype='dotted')+
      facet_wrap(~variable, scales = "free", labeller = label_both, ncol = 2)+
      theme_classic()+
      ylab("")
    
  }

}
pp = (get_plot("Slope",T)|get_plot("Slope_dif",F)) /  (get_plot("Threshold",T)|get_plot("Threshold_dif",F)) /  (get_plot("Lapse",T) | grouplevel_con+ylab("")+ theme(axis.text.x = element_text(angle = 30, vjust = 0.7, hjust=0.5)))

ggsave(here::here("figures","contraction_subjectlevel_HRDT.png"), pp, dpi = 300, height = 6, width = 8)



```



```{r}
n_draws = 10000
priors <- tibble(
  variable = c(
    "gm[1]", "gm[2]", "gm_alpha",
    "tau_u[1]", "tau_u[2]", "tau_u_alpha"
  ),
  mean = c(
    2, -4, 1.5,
     0,   0, 0
  ),
  sd = c(
     1, 2, .5,
     1, 2, .5
  )
)

draws_df <- priors %>%
  mutate(draws = map2(mean, sd, ~ rnorm(n_draws, .x, .y))) %>%
  unnest(draws)

prior_sd <- draws_df %>%
  group_by(variable) %>%
  summarise(
    pre_var = var(draws),
    .groups = "drop"
  )

post_sd = as_draws_df(RRST_weibull_priors$draws(c("gm","tau_u","gm_alpha","tau_u_alpha"))) %>% select(-contains(".")) %>% 
  pivot_longer(everything()) %>% group_by(name) %>% 
  summarize(post_var = sd(value)^2) %>% 
  rename(variable = name)

label_map <- c(
  "gm[1]"    = "μ[Slope]",
  "gm[2]"    = "μ[Lapse]",
  "gm_alpha"    = "μ[Threshold]",
  "tau_u[1]" = "σ[Slope]",
  "tau_u[2]" = "σ[Lapse]",
  "tau_u_alpha" = "σ[Threshold]"
)

grouplevel_con = inner_join(post_sd, prior_sd) %>%
  mutate(contraction = 1 - (post_var / pre_var)) %>%
  mutate(variable2 = recode(variable, !!!label_map)) %>%
  mutate(variable = "Grouplevel") %>% 
  ggplot(aes(x = variable2, y = contraction)) +
  geom_point() +
  geom_hline(aes(yintercept=1),alpha=.5,linetype='dotted')+
  geom_hline(aes(yintercept=0),alpha=.5,linetype='dotted')+
  scale_x_discrete(labels = function(x) parse(text = x)) +
  xlab("")+
  theme_classic()+
  facet_wrap(~variable, labeller = label_both)



```

```{r, fig.width=12,fig.height=6}
n_draws = 10000

df <- tibble(
  variable = c(
    "gm[1]", "gm[2]", "gm_alpha",
    "tau_u[1]", "tau_u[2]", "tau_u_alpha"
  ),
  mean = c(
    2, -4, 1.5,
    0, 0, 0
  ),
  sd = c(
    1, 2, .5,
    1, 2, .5
  )
) %>%
  mutate(
    p = case_when(
      variable == "gm[1]" ~ 1,
      variable == "gm[2]" ~ 2,
      variable == "gm_alpha" ~ 3,
      variable == "tau_u[1]" ~ 1,
      variable == "tau_u[2]" ~ 2,
      variable == "tau_u_alpha" ~ 3
    ),
    type = case_when(
      str_detect(variable,"gm") ~ "gm",
      str_detect(variable,"tau") ~ "tau_u"
    )
  ) %>%
  select(p,type,mean,sd) %>%
  group_by(p,type) %>%
  summarise(
    draw=list(rnorm(n_draws,mean,sd)),
    .groups="drop"
  ) %>%
  unnest(draw) %>%
  group_by(p,type) %>%
  mutate(draw_id=row_number()) %>%
  ungroup() %>%
  pivot_wider(
    names_from=type,
    values_from=draw
  )


priorvar = df %>%
  mutate(
    z = rnorm(n()),
    theta = gm + tau_u * z,
    theta_name = paste0("theta[", p, "]")
  ) %>%
  group_by(theta_name) %>%
  summarise(prior_variance = var(theta)) %>% 
  ungroup() %>% 
  mutate(variable = ifelse(theta_name == "theta[1]","Slope",
                            ifelse(theta_name == "theta[2]","Lapse",
                                   ifelse(theta_name == "theta[3]","Threshold",NA))),
         theta_name = NULL)



post_param =
  as_draws_df(RRST_weibull_priors$draws("param")) %>%
  select(-contains(".")) %>%
  mutate(draw=1:n()) %>%
  pivot_longer(-draw) %>%
  mutate(
    subject=as.integer(str_match(name,"\\[(\\d+),(\\d+)\\]")[,2]),
    variable=as.integer(str_match(name,"\\[(\\d+),(\\d+)\\]")[,3])
  )

post_alpha =
  as_draws_df(RRST_weibull_priors$draws("alpha")) %>%
  select(-contains(".")) %>%
  mutate(draw=1:n()) %>%
  pivot_longer(-draw) %>%
  mutate(
    subject=as.integer(str_match(name,"\\[(\\d+)\\]")[,2]),
    variable=3
  )

post_sd_sub =
  bind_rows(post_param,post_alpha) %>%
  group_by(subject,variable) %>%
  summarise(
    post_var=var(value),
    .groups="drop"
  ) %>%
  mutate(
    variable=recode(as.character(variable),
      "1"="Slope",
      "2"="Lapse",
      "3"="Threshold"
    )
  )


p1 =
  inner_join(priorvar,post_sd_sub,by="variable") %>%
  mutate(contraction=1-(post_var/prior_variance)) %>%
  ggplot(aes(x=subject,y=contraction))+
  geom_point(alpha=0.3)+
  geom_hline(yintercept=1,alpha=.5,linetype='dotted')+
  geom_hline(yintercept=0,alpha=.5,linetype='dotted')+
  facet_wrap(~variable,scales="free",labeller=label_both,ncol=2)+
  theme_classic()

```


```{r, fig.width=12,fig.height=10}
get_plot = function(variable2, axis_title){
  
  if(axis_title){
    inner_join(priorvar, post_sd_sub) %>% 
      filter(variable == variable2) %>% 
      mutate(contraction = 1 - (post_var / prior_variance)) %>% 
      ggplot(aes(x = subject, y = contraction))+
      geom_point(alpha = 0.3)+
      geom_hline(aes(yintercept=1),alpha=.5,linetype='dotted')+
      geom_hline(aes(yintercept=0),alpha=.5,linetype='dotted')+
      facet_wrap(~variable, scales = "free", labeller = label_both, ncol = 2)+
      theme_classic()
  }else{
    inner_join(priorvar, post_sd_sub) %>% 
      filter(variable == variable2) %>% 
      mutate(contraction = 1 - (post_var / prior_variance)) %>% 
      ggplot(aes(x = subject, y = contraction))+
      geom_point(alpha = 0.3)+
      geom_hline(aes(yintercept=1),alpha=.5,linetype='dotted')+
      geom_hline(aes(yintercept=0),alpha=.5,linetype='dotted')+
      facet_wrap(~variable, scales = "free", labeller = label_both, ncol = 2)+
      theme_classic()+
      ylab("")
    
  }

}
pp = (get_plot("Slope",T)| get_plot("Threshold",T)) /  (get_plot("Lapse",T) | grouplevel_con+ylab("")+ theme(axis.text.x = element_text(angle = 30, vjust = 0.7, hjust=0.5)))

ggsave(here::here("figures","contraction_subjectlevel_RRST.png"), pp, dpi = 300, height = 6, width = 8)



```

