---
title: "Figure3"
output: html_document
---

```{r}
source(here::here("scripts","utility.R"))
library(loo)
library(tidyverse)
library(patchwork)

logit<-function(x){
  y<-log(x/(1-x))
  return(y)
}
```

```{r}
gu<-readRDS(here::here("results","recovery","Gumbel_datasets.RData"))
ga<-readRDS(here::here("results","recovery","Gaussian_datasets.RData"))

mod_comp<-tibble(
  winning_model=rep(NaN,200),
  generative_model=rep(NaN,200),
  any_pareto_k=rep(NaN,200),
  significant=rep(NaN,200),
  any_bad_rhat=rep(NaN,200),
  sum_div=rep(NaN,200)
  )
for(idx in 1:100){
  if(is.list(ga[[idx]])){
    mr<-ga[idx][[1]][[2]] %>%
      filter(variable=='gm[1]')

    mod_comp$generative_model[idx]<-1

    if(mr$models[1]=='Gaussian'){
      mod_comp$winning_model[idx]<-1
    }else{
      mod_comp$winning_model[idx]<-2
    }

    mod_comp$significant[idx]<-(min(mr$elpd_diff)/2*mr$se_diff[mr$elpd_diff==min(mr$elpd_diff)])<(-2)


    mod_comp$any_pareto_k[idx]<-sum(mr$pareto_k_over_0.7)>1
    mod_comp$sum_div[idx]<-sum(mr$mean_div)>0
    all_rhats<-c(ga[[idx]][[3]][[2]]$rhat,ga[[idx]][[4]][[2]]$rhat,
                 ga[[idx]][[3]][[1]]$rhat,ga[[idx]][[4]][[1]]$rhat)
    mod_comp$any_bad_rhat[idx]<-any(all_rhats>1.05,na.rm=TRUE)
  }
}
for(idx in 1:100){
  mdx=idx+100

  if(is.list(gu[[idx]])){
    mr<-gu[idx][[1]][[2]] %>%
      filter(variable=='gm[1]')

    mod_comp$generative_model[mdx]<-2

    if(mr$models[1]=='Gaussian'){
      mod_comp$winning_model[mdx]<-1
    }else{
      mod_comp$winning_model[mdx]<-2
    }

    mod_comp$significant[mdx]<-(min(mr$elpd_diff)/2*mr$se_diff[mr$elpd_diff==min(mr$elpd_diff)])<(-2)


    mod_comp$any_pareto_k[mdx]<-sum(mr$pareto_k_over_0.7)>1
    mod_comp$sum_div[mdx]<-sum(mr$mean_div)>0
    all_rhats<-c(gu[[idx]][[3]][[2]]$rhat,gu[[idx]][[4]][[2]]$rhat,
                 gu[[idx]][[3]][[1]]$rhat,gu[[idx]][[4]][[1]]$rhat)
    mod_comp$any_bad_rhat[mdx]<-any(all_rhats>1.05,na.rm=TRUE)
  }
}


mod_comp<-mod_comp %>% filter(sum_div==0,!any_bad_rhat,!is.na(generative_model))
test<-tibble(n=rep(NaN,4),n_sig=rep(NaN,4))
for(gen in 1:2){
  for(win in 1:2){
    test$generative_model[win+(gen-1)*2]=gen
    test$winning_model[win+(gen-1)*2]=win
    test$n[win+(gen-1)*2]=sum(mod_comp$winning_model[mod_comp$generative_model==gen]==win)
    test$n_sig[win+(gen-1)*2]=sum(mod_comp$winning_model[mod_comp$generative_model==gen & mod_comp$significant==1]==win)
    test$n_tot[win+(gen-1)*2]=sum(mod_comp$generative_model==gen)
  }
}

test<-test %>%
  mutate(
    prop=n/n_tot,
    prop_sig=n_sig/n_tot,
    prop_lb=qbeta(.05,1+n,1+n_tot-n),
    prop_ub=qbeta(.95,1+n,1+n_tot-n)
    )
test %>% 
  ggplot()+
  geom_tile(aes(x=as.factor(generative_model),y=as.factor(winning_model),fill=n/n_tot))+
  geom_text(aes(x=as.factor(generative_model),y=as.factor(winning_model),label=paste0(round(prop,2),'\n[',round(prop_lb,2),' - ',round(prop_ub,2),']')),color=rgb(.4,.4,.4))+
  xlab('Generative model')+
  ylab('Winning model')+
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text.y = element_text(angle = 90,hjust=0.5))+
  scale_x_discrete(breaks=1:2,labels = c('Gaussian','Gumbel'))+
  scale_y_discrete(breaks=1:2,labels = c('Gaussian','Gumbel'))+
  scale_fill_gradient(low = "black", high = "white",limits=c(0,1))+
  ggtitle('Model recovery')

  
ggsave(here::here("figures",'Figure3A.png'),units = 'cm',width = 7,height = 6.5)

```

```{r}
classify_model_fit <- function(data_list, idx, model_name, model_slot){
  if(!is.list(data_list[[idx]]))
    return('initialization failure')
  mr <- data_list[idx][[1]][[2]] %>% filter(variable=='gm[1]', models==model_name)
  sum_div_flag      <- mr$mean_div > 0
  all_rhats         <- c(data_list[[idx]][[model_slot]][[2]]$rhat,
                         data_list[[idx]][[model_slot]][[1]]$rhat)
  any_bad_rhat_flag <- any(all_rhats > 1.05, na.rm=TRUE)
  case_when(
    sum_div_flag & any_bad_rhat_flag   ~ 'divergences + poor rhat',
    sum_div_flag                       ~ 'divergences',
    any_bad_rhat_flag                  ~ 'poor rhat',
    TRUE                               ~ 'survived'
  )
}

model_info <- list(Gaussian=3, Gumbel=4)

exclusion_summary <- map_dfr(names(model_info), function(model_name){
  slot <- model_info[[model_name]]
  bind_rows(
    map_dfr(1:100, ~tibble(generative_dataset='Gaussian', fitted_model=model_name,
                           exclusion=classify_model_fit(ga, .x, model_name, slot))),
    map_dfr(1:100, ~tibble(generative_dataset='Gumbel',   fitted_model=model_name,
                           exclusion=classify_model_fit(gu, .x, model_name, slot)))
  )
}) %>%
  count(generative_dataset, fitted_model, exclusion) %>%
  pivot_wider(names_from=exclusion, values_from=n, values_fill=0) %>%
  relocate(generative_dataset, fitted_model,
           any_of(c('initialization failure','divergences','divergences + poor rhat','poor rhat','survived')))

print(exclusion_summary)
```

```{r}
gu<-readRDS(here::here("results","recovery","Gumbel_datasets.RData"))
ga<-readRDS(here::here("results","recovery","Gaussian_datasets.RData"))

mod_comp<-tibble(
  winning_model=rep(NaN,200),
  generative_model=rep(NaN,200),
  any_pareto_k=rep(NaN,200),
  significant=rep(NaN,200),
  meanrhat=rep(NaN,200),
  sum_div=rep(NaN,200)
  )
for(idx in 1:100){
  if(is.list(ga[[idx]])){
    mr<-ga[idx][[1]][[2]] %>% 
      filter(variable=='gm[1]')
    
    mod_comp$generative_model[idx]<-1
  
    if(mr$models[1]=='Gaussian'){
      mod_comp$winning_model[idx]<-1
    }else{
      mod_comp$winning_model[idx]<-2
    }
    
    mod_comp$significant[idx]<-(min(mr$elpd_diff)/2*mr$se_diff[mr$elpd_diff==min(mr$elpd_diff)])<(-2)
    
    
    mod_comp$any_pareto_k[idx]<-sum(mr$pareto_k_over_0.7)>1
    mod_comp$sum_div[idx]<-sum(mr$mean_div)>0
    mod_comp$meanrhat[idx]<-mean(mr$meanrhat)>1.01
  }
}
for(idx in 1:100){
  mdx=idx+100
  
  if(is.list(gu[[idx]])){
    mr<-gu[idx][[1]][[2]] %>% 
      filter(variable=='gm[1]')
    
    mod_comp$generative_model[mdx]<-2
  
    if(mr$models[1]=='Gaussian'){
      mod_comp$winning_model[mdx]<-1
    }else{
      mod_comp$winning_model[mdx]<-2
    }
    
    mod_comp$significant[mdx]<-(min(mr$elpd_diff)/2*mr$se_diff[mr$elpd_diff==min(mr$elpd_diff)])<(-2)
    
    
    mod_comp$any_pareto_k[mdx]<-sum(mr$pareto_k_over_0.7)>1
    mod_comp$sum_div[mdx]<-sum(mr$mean_div)>0
    mod_comp$meanrhat[mdx]<-mean(mr$meanrhat)>1.01
  }
}


mod_comp<-mod_comp %>% filter(!is.na(winning_model))
test<-tibble(n=rep(NaN,4),n_sig=rep(NaN,4))
for(gen in 1:2){
  for(win in 1:2){
    test$generative_model[win+(gen-1)*2]=gen
    test$winning_model[win+(gen-1)*2]=win
    test$n[win+(gen-1)*2]=sum(mod_comp$winning_model[mod_comp$generative_model==gen]==win)
    test$n_sig[win+(gen-1)*2]=sum(mod_comp$winning_model[mod_comp$generative_model==gen & mod_comp$significant==1]==win)
    test$n_tot[win+(gen-1)*2]=sum(mod_comp$generative_model==gen)
  }
}

test<-test %>%
  mutate(
    prop=n/n_tot,
    prop_sig=n_sig/n_tot,
    prop_lb=qbeta(.05,1+n,1+n_tot-n),
    prop_ub=qbeta(.95,1+n,1+n_tot-n)
    )
test %>% 
  ggplot()+
  geom_tile(aes(x=as.factor(generative_model),y=as.factor(winning_model),fill=n/n_tot))+
  geom_text(aes(x=as.factor(generative_model),y=as.factor(winning_model),label=paste0(round(prop,2),'\n[',round(prop_lb,2),' - ',round(prop_ub,2),']')),color=rgb(.4,.4,.4))+
  xlab('Generative model')+
  ylab('Winning model')+
  theme_minimal()+
  theme(legend.position = 'none',
         axis.text.y = element_text(angle = 90,hjust=0.5))+
  scale_x_discrete(breaks=1:2,labels = c('Gaussian','Gumbel'))+
  scale_y_discrete(breaks=1:2,labels = c('Gaussian','Gumbel'))+
  scale_fill_gradient(low = "black", high = "white",limits=c(0,1))+
  ggtitle('Model recovery')

  
ggsave(here::here("figures",'Figure3A_with_div.png'),units = 'cm',width = 7,height = 6.5)

```

```{r}
mr_gaussian <- map_dfr(1:100, function(idx){
  if(is.list(ga[[idx]])){
      md<-ga[idx][[1]][[2]] %>% filter(variable=='gm[1]',models=='Gaussian')
      if(md$mean_div==0 & !any(ga[[idx]][[3]][[2]]$rhat>1.05)){
        ga[[idx]][[3]][[2]] %>%
        mutate(idx = idx,dataset='gaussian')
      }
    }
  }
)
mr_gumbel <- map_dfr(1:100, function(idx){
  if(is.list(gu[[idx]])){
      md<-gu[idx][[1]][[2]] %>% filter(variable=='gm[1]',models=='Gumbel')
      if(md$mean_div==0 & !any(gu[[idx]][[4]][[2]]$rhat>1.05)){
        gu[[idx]][[4]][[2]] %>%
        mutate(idx = idx+100,dataset='gumbel')
      }
    }
  }
)

n_d_ga<-length(unique(mr_gaussian$idx))
n_d_gu<-length(unique(mr_gumbel$idx))

mr_all <- bind_rows(mr_gaussian, mr_gumbel)%>%
  mutate(recovered=simulated>q5&simulated<q95)

recovery_rate<-
  mr_all %>% 
  filter(!is.na(q5)) %>% 
  group_by(variable,dataset) %>% 
  summarise(
    n=sum(!is.na(recovered)),
    recovery_rate=mean(recovered),
    lb=qbeta(.05,1+recovery_rate*n,1+(1-recovery_rate)*n),
    ub=qbeta(.95,1+recovery_rate*n,1+(1-recovery_rate)*n)
    )

combined<-
  mr_all %>% 
  full_join(recovery_rate)

combined %>% 
  filter(variable=='mu_alpha') %>% 
  ggplot()+
  geom_abline(aes(intercept = 0,slope=1))+
  geom_linerange(aes(x=simulated,ymin=q5,ymax=q95,color=dataset))+
  geom_text(aes(x=25,y=-40+10*as.numeric(dataset=='gaussian'),label=sprintf("%.2f [%.2f - %.2f]",round(recovery_rate,2),round(lb,2),round(ub,2)),color=dataset))+
  theme_minimal()+
  scale_color_manual(values = c('#0072B2','#E69F00'))+
  theme(legend.position = 'none')+
  xlab('Ground truth')+
  ylab('Estimate')+
  ggtitle('Group mean threshold')


ggsave(here::here("figures",'Figure3B.png'),units = 'cm',width = 8,height = 6.5)

combined %>% 
  filter(variable=='mu_beta') %>% 
  ggplot()+
  geom_abline(aes(intercept = 0,slope=1))+
  geom_linerange(aes(x=simulated,ymin=q5,ymax=q95,color=dataset))+
  geom_text(aes(x=-2.5,y=-1+.35*as.numeric(dataset=='gaussian'),label=sprintf("%.2f [%.2f - %.2f]",round(recovery_rate,2),round(lb,2),round(ub,2)),color=dataset))+
  theme_minimal()+
  scale_color_manual(values = c('#0072B2','#E69F00'))+
  theme(legend.position = 'none')+
  xlab('Ground truth')+
  ylab('Estimate')+
  ggtitle('Group mean log(slope)')


ggsave(here::here("figures",'Figure3C.png'),units = 'cm',width = 8,height = 6.5)

combined %>% 
  filter(variable=='mu_lambda') %>% 
  ggplot()+
  geom_abline(aes(intercept = 0,slope=1))+
  geom_linerange(aes(x=simulated,ymin=q5,ymax=q95,color=dataset))+
  geom_text(aes(x=-3,y=-10+.8*as.numeric(dataset=='gaussian'),label=sprintf("%.2f [%.2f - %.2f]",round(recovery_rate,2),round(lb,2),round(ub,2)),color=dataset))+
  theme_minimal()+
  scale_color_manual(values = c('#0072B2','#E69F00'))+
  theme(legend.position = 'none')+
  xlab('Ground truth')+
  ylab('Estimate')+
  ggtitle('Group mean half-logit(lapse)')+
  ylim(c(-10,0))

ggsave(here::here("figures",'Figure3D.png'),units = 'cm',width = 8,height = 6.5)

combined %>% 
  filter(variable%in%c('tau_alpha','tau_beta','tau_lambda')) %>% 
  ggplot()+
  geom_abline(aes(intercept = 0,slope=1))+
  geom_linerange(aes(x=simulated,ymin=q5,ymax=q95,color=dataset))+
  theme_minimal()+
  scale_color_manual(values = c('#0072B2','#E69F00'))+
  theme(legend.position = 'none')+
  xlab('Ground truth')+
  ylab('Estimate')+
  facet_wrap(variable~.,scales = 'free')

ggsave(here::here("figures",'FigureRecoveryTaus.png'),units = 'cm',width = 18,height = 8)
```



## subject level parameter recovery:

```{r}
mr_gaussian <- map_dfr(1:100, function(idx){
  if(is.list(ga[[idx]])){
      md<-ga[idx][[1]][[2]] %>% filter(variable=='gm[1]',models=='Gaussian')
      if(md$mean_div==0 & !any(ga[[idx]][[3]][[2]]$rhat>1.05)){
        ga[[idx]][[3]][[1]] %>%
        mutate(idx = idx,dataset='gaussian')
      }
    }
  }
)
mr_gumbel <- map_dfr(1:100, function(idx){
  if(is.list(gu[[idx]])){
      md<-gu[idx][[1]][[2]] %>% filter(variable=='gm[1]',models=='Gumbel')
      if(md$mean_div==0 & !any(gu[[idx]][[4]][[2]]$rhat>1.05)){
        gu[[idx]][[4]][[1]] %>%
        mutate(idx = idx+100,dataset='gumbel')
      }
    }
  }
)

n_d_ga<-length(unique(mr_gaussian$idx))
n_d_gu<-length(unique(mr_gumbel$idx))

mr_all <- bind_rows(mr_gaussian, mr_gumbel) %>% 
  mutate(participant=as.numeric(participant))%>% 
  mutate(recovered=simulated>q5&simulated<q95)


recovery_rate<-
  mr_all %>% 
  filter(!is.na(q5)) %>% 
  group_by(variable,dataset) %>% 
  summarise(
    n=sum(!is.na(recovered)),
    recovery_rate=mean(recovered),
    lb=qbeta(.05,1+recovery_rate*n,1+(1-recovery_rate)*n),
    ub=qbeta(.95,1+recovery_rate*n,1+(1-recovery_rate)*n)
    )

combined<-
  mr_all %>% 
  full_join(recovery_rate)

a<-
  combined %>% 
  filter(variable=='alpha') %>% 
  ggplot()+
  geom_abline(aes(intercept = 0,slope=1))+
  geom_linerange(aes(x=simulated,ymin=q5,ymax=q95,color=dataset),alpha=.5)+
  geom_text(aes(x=-25,y=50+10*as.numeric(dataset=='gaussian'),label=sprintf("%.2f [%.2f - %.2f]",round(recovery_rate,2),round(lb,2),round(ub,2)),color=dataset),size=2)+
  theme_minimal()+
  scale_color_manual(values = c('#0072B2','#E69F00'))+
  theme(legend.position = 'none')+
  xlab('Ground truth')+
  ylab('Estimate')+
  ggtitle('Threshold')

b<-
  combined %>% 
  filter(variable=='beta') %>% 
  ggplot()+
  geom_abline(aes(intercept = 0,slope=1))+
  geom_linerange(aes(x=log(simulated),ymin=log(q5),ymax=log(q95),color=dataset),alpha=.5)+
  geom_text(aes(x=-3,y=5+2*as.numeric(dataset=='gaussian'),label=sprintf("%.2f [%.2f - %.2f]",round(recovery_rate,2),round(lb,2),round(ub,2)),color=dataset),size=2)+
  theme_minimal()+
  scale_color_manual(values = c('#0072B2','#E69F00'))+
  theme(legend.position = 'none')+
  xlab('Ground truth')+
  ylab('Estimate')+
  ggtitle('log(slope)')

l<-
  combined %>% 
  filter(variable=='lambda') %>%
  ggplot()+
  geom_abline(aes(intercept = 0,slope=1))+
  geom_linerange(aes(x=logit(2*simulated),ymin=logit(2*q5),ymax=logit(2*q95),color=dataset),alpha=.5)+
  geom_text(aes(x=-8,y=2+2*as.numeric(dataset=='gaussian'),label=sprintf("%.2f [%.2f - %.2f]",round(recovery_rate,2),round(lb,2),round(ub,2)),color=dataset),size=2)+
  theme_minimal()+
  scale_color_manual(values = c('#0072B2','#E69F00'))+
  theme(legend.position = 'none')+
  xlab('Ground truth')+
  ylab('Estimate')+
  ggtitle('logit(lapse rate)')


fig_recovery <- a + b + l
print(fig_recovery)
ggsave(
  here::here("figures","FigureSubjectRecov.png"),
  fig_recovery,
  units = "cm",
  width = 18,
  height = 8
)

```

```{r}
generative_gaussian <- read_csv(here::here("simulated_data","model_parameter_recovery","R_gaussian.csv"), show_col_types = FALSE) %>%
  distinct(idx, mu_alpha, mu_beta, mu_lambda, tau_alpha, tau_beta, tau_lambda) %>%
  mutate(generative_model = "Gaussian")

generative_gumbel <- read_csv(here::here("simulated_data","model_parameter_recovery","R_gumbel.csv"), show_col_types = FALSE) %>%
  distinct(idx, mu_alpha, mu_beta, mu_lambda, tau_alpha, tau_beta, tau_lambda) %>%
  mutate(generative_model = "Gumbel")

is_retained <- function(data_list, idx, model_name, model_slot){
  if(!is.list(data_list[[idx]])) return(FALSE)
  md <- data_list[idx][[1]][[2]] %>% filter(variable == 'gm[1]', models == model_name)
  md$mean_div == 0 & !any(data_list[[idx]][[model_slot]][[2]]$rhat > 1.05, na.rm = TRUE)
}

generative_gaussian$retained <- map_lgl(generative_gaussian$idx, ~is_retained(ga, .x, 'Gaussian', 3))
generative_gumbel$retained   <- map_lgl(generative_gumbel$idx,   ~is_retained(gu, .x, 'Gumbel', 4))

generative_values <- bind_rows(generative_gaussian, generative_gumbel) %>%
  mutate(status = if_else(retained, 'retained', 'excluded')) %>%
  pivot_longer(cols = c(mu_alpha, mu_beta, mu_lambda, tau_alpha, tau_beta, tau_lambda),
               names_to = 'variable', values_to = 'generative_value') %>%
  mutate(variable = factor(variable, levels = c('mu_alpha','mu_beta','mu_lambda',
                                                  'tau_alpha','tau_beta','tau_lambda')))

generative_values %>%
  ggplot(aes(x = status, y = generative_value, color = generative_model)) +
  geom_jitter(width = 0.15, alpha = 0.6, size = 1.5) +
  stat_summary(fun = median, geom = "crossbar", width = 0.4, color = 'black', fatten = 1) +
  facet_wrap(~ variable, scales = 'free_y', nrow = 2) +
  scale_color_manual(values = c(Gaussian = '#0072B2', Gumbel = '#E69F00')) +
  theme_minimal() +
  theme(legend.position = 'top') +
  xlab(NULL) +
  ylab('Generative (ground truth) value') +
  labs(color = 'Generative model') +
  ggtitle('Generative parameter values by dataset exclusion status')

ggsave(here::here("figures","FigureGenerativeByExclusion.png"), units = 'cm', width = 20, height = 12)
```